storage: FILE #FILE, MARIADB, POSTGRES, MYSQL, REDIS
redis:
  host: '127.0.0.1'
  port: 6379
  bans-key: 'bans'
  mutes-key: 'mutes'
  history-key: 'punish-history'
  password: ''
  database: 0

sql:
  host: '127.0.0.1'
  port: 3306
  username: 'root'
  password: ''
  bans-table: 'bans'
  mutes-table: 'mutes'
  history-table: 'history'
  database: 'proxybans'
  useSSL: false

#Настройка кулдаунов, максимального времени наказания и веса для групп.
# Параметр "weight" определяет место группы в цепочке наказаний.
# Группу с весом 0 - могут забанить любые группы выше, если у игроков одинаковые группы -
# соответственно вес их групп будет совпадать, а значит они смогут наказывать друг друга.

#Если группы игрока нет в этом списке, но права на пользование плагином есть -
# все запрашиваемые параметры будут определяться как 0.
groups:
  default:
    weight: 0
    maxPunishTime:
      tempban: 10m
      tempmute: 30m
    cooldown:
      ban: 5m
      tempban: 1m
      mute: 5m
      tempmute: 1m
      kick: 5m
  admin:
    weight: 1
    maxPunishTime:
      tempban: 150h
      tempmute: 10h
    cooldown:
      ban: 2m
      tempban: 1m
      mute: 5m
      tempmute: 1m
      kick: 1m

#Список игроков, которых не могут наказывать обычные пользователи плагина.
protectedPlayers:
  - klesaak

dateFormat:
  format: "dd.MM.yyyy HH:mm:ss"
  locale: "ru"
  timeZone: "Europe/Moscow"

#Команды, которые будут блокироваться плагином, если игроку выдан мут. Автоматически обрабатываются команды типа /me -> /essentials:me
blockedCommandsOnMute:
  - /me
  - /bc
  - /broadcast
  - /tell
  - /w
  - /msg