storage: FILE #FILE, MYSQL, REDIS
redis:
  host: '127.0.0.1'
  port: 6379
  bans-key: 'bans'
  mutes-key: 'mutes'
  history-key: 'punish-history'
  password:
  database: 0

mysql:
  host: '127.0.0.1'
  port: 3306
  username: 'root'
  password: ''
  bans-table: 'bans'
  mutes-table: 'mutes'
  history-table: 'history'
  database: 'proxybans'
  useSSL: false


groups:
  defaults:
    weight: 0
    maxPunishTime:
      tempban: 10m
      tempmute: 30m
      tempipban: 1h
    cooldown:
      ban: 5m
      tempban: 1m
      mute: 5m
      tempmute: 1m
      kick: 5m
  admin:
    weight: 1
    maxPunishTime:
      tempban: 150h
      tempmute: 10h
      tempipban: 1h
    cooldown:
      ban: 2m
      tempban: 1m
      mute: 5m
      tempmute: 1m
      kick: 1m

protectedPlayers:
  - klesaak

dateFormat:
  format: "dd.MM.yyyy HH:mm:ss"
  locale: "ru"
  timeZone: "Europe/Moscow"

blockedCommandsOnMute:
  - /me
  - /bc
  - /broadcast
  - /tell
  - /w
  - /msg